# Import Library

In [282]:
import pandas as pd
#import numpy as np
#from datetime import datetime
#import matplotlib.pyplot as plt
#import seaborn as sns

# Load and Inspect Dataset

In [283]:
df = pd.read_parquet('nigerian_personal_loans_full.parquet', engine='pyarrow')
print(df.head())

       loan_id   customer_id application_date disbursement_date loan_status  \
0  LN-00000001  CUS-00496440       2024-02-01               NaT    rejected
1  LN-00000002  CUS-00852236       2024-12-30               NaT    rejected
2  LN-00000003  CUS-00247986       2023-05-11        2023-05-21   disbursed
3  LN-00000004  CUS-00959435       2024-07-18        2024-07-31   disbursed
4  LN-00000005  CUS-00434836       2024-02-05        2024-02-15   disbursed

   principal_ngn  interest_rate_annual  tenor_months  monthly_payment_ngn  \
0       250000.0              0.229316            12         23510.831907
1       370000.0              0.263015            12         35400.449102
2       450000.0              0.235424            12         42452.227127
3       200000.0              0.236392            12         18877.014774
4       270000.0              0.288615            18         18657.387006

      salary_ngn  debt_to_income_ratio  credit_score employment_type  \
0   77316.610517              0.304085           696  private_sector
1  687453.897173              0.051495           659      government
2  586733.820027              0.072353           616  private_sector
3  342758.601626              0.055074           539      government
4  259973.901819              0.071766           711  private_sector

  loan_purpose      state  salary_detected  dpd_current  dpd_max_90d  \
0     personal    Plateau             True            0            0
1      medical     Jigawa             True            0            0
2      medical      Lagos             True            0            0
3    education  Akwa Ibom            False            0            0
4     personal      Niger             True            0            0

   default_90d  default_180d
0        False         False
1        False         False
2        False         False
3        False         False
4        False         False

In [284]:
# View first five row
df.head()

,loan_id,customer_id,application_date,disbursement_date,loan_status,principal_ngn,interest_rate_annual,tenor_months,monthly_payment_ngn,salary_ngn,debt_to_income_ratio,credit_score,employment_type,loan_purpose,state,salary_detected,dpd_current,dpd_max_90d,default_90d,default_180d
0,LN-00000001,CUS-00496440,2024-02-01,NaT,rejected,250000.0,0.229316,12,23510.831907,77316.610517,0.304085,696,private_sector,personal,Plateau,True,0,0,False,False
1,LN-00000002,CUS-00852236,2024-12-30,NaT,rejected,370000.0,0.263015,12,35400.449102,687453.897173,0.051495,659,government,medical,Jigawa,True,0,0,False,False
2,LN-00000003,CUS-00247986,2023-05-11,2023-05-21,disbursed,450000.0,0.235424,12,42452.227127,586733.820027,0.072353,616,private_sector,medical,Lagos,True,0,0,False,False
3,LN-00000004,CUS-00959435,2024-07-18,2024-07-31,disbursed,200000.0,0.236392,12,18877.014774,342758.601626,0.055074,539,government,education,Akwa Ibom,False,0,0,False,False
4,LN-00000005,CUS-00434836,2024-02-05,2024-02-15,disbursed,270000.0,0.288615,18,18657.387006,259973.901819,0.071766,711,private_sector,personal,Niger,True,0,0,False,False

In [285]:
# View last five row
df.tail()

,loan_id,customer_id,application_date,disbursement_date,loan_status,principal_ngn,interest_rate_annual,tenor_months,monthly_payment_ngn,salary_ngn,debt_to_income_ratio,credit_score,employment_type,loan_purpose,state,salary_detected,dpd_current,dpd_max_90d,default_90d,default_180d
1999995,LN-01999996,CUS-00680212,2022-10-29,2022-11-12,disbursed,3190000.0,0.217794,6,565945.977162,212071.458442,2.000000,719,government,education,Abuja (FCT),True,0,0,False,False
1999996,LN-01999997,CUS-00195314,2024-06-20,NaT,rejected,1050000.0,0.199480,12,97240.095222,143833.348128,0.676061,560,government,personal,Rivers,True,0,0,False,False
1999997,LN-01999998,CUS-00229985,2021-06-24,NaT,rejected,150000.0,0.269759,12,14400.843469,218060.399703,0.066041,642,self_employed,business,Oyo,False,0,0,False,False
1999998,LN-01999999,CUS-00009993,2021-07-13,NaT,rejected,900000.0,0.281884,6,162570.952718,371119.315373,0.438056,628,government,business,Kano,True,0,0,False,False
1999999,LN-02000000,CUS-00099699,2021-07-06,2021-07-16,disbursed,110000.0,0.205301,6,19446.637333,90720.029460,0.214359,539,self_employed,medical,Jigawa,False,167,15,True,True

In [286]:
# Let's check the dimension
df.shape

(2000000, 20)

In [287]:
df.describe(include="all")

,loan_id,customer_id,application_date,disbursement_date,loan_status,principal_ngn,interest_rate_annual,tenor_months,monthly_payment_ngn,salary_ngn,debt_to_income_ratio,credit_score,employment_type,loan_purpose,state,salary_detected,dpd_current,dpd_max_90d,default_90d,default_180d
count,2000000,2000000,2000000,1190910,2000000,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2000000,2000000,2000000,2000000,2.000000e+06,2.000000e+06,2000000,2000000
unique,2000000,864619,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,6,37,2,NaN,NaN,2,2
top,LN-00000001,CUS-00048650,NaN,NaN,disbursed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,private_sector,debt_consolidation,Lagos,True,NaN,NaN,False,False
freq,1,13,NaN,NaN,1190910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,899188,500322,476927,1100096,NaN,NaN,1875628,1831614
mean,NaN,NaN,2022-12-31 08:58:01.200001792,2023-01-10 19:44:53.855959,NaN,3.693762e+05,2.401765e-01,1.208589e+01,4.569071e+04,2.513880e+05,2.930472e-01,6.195735e+02,NaN,NaN,NaN,NaN,1.530846e+01,4.639770e+00,NaN,NaN
min,NaN,NaN,2021-01-01 00:00:00,2021-01-08 00:00:00,NaN,5.000000e+04,1.500000e-01,3.000000e+00,1.733266e+03,3.000000e+04,7.347331e-04,3.000000e+02,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,NaN,NaN
25%,NaN,NaN,2022-01-01 00:00:00,2022-01-11 00:00:00,NaN,1.600000e+05,2.130216e-01,6.000000e+00,1.538677e+04,1.152108e+05,6.781543e-02,5.660000e+02,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,NaN,NaN
50%,NaN,NaN,2022-12-31 00:00:00,2023-01-11 00:00:00,NaN,2.700000e+05,2.400536e-01,1.200000e+01,2.877058e+04,1.917162e+05,1.518942e-01,6.200000e+02,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,NaN,NaN
75%,NaN,NaN,2024-01-01 00:00:00,2024-01-11 00:00:00,NaN,4.600000e+05,2.670563e-01,1.200000e+01,5.489873e+04,3.170231e+05,3.433757e-01,6.740000e+02,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,NaN,NaN
max,NaN,NaN,2024-12-30 00:00:00,2025-01-13 00:00:00,NaN,5.000000e+06,3.500000e-01,3.600000e+01,1.750188e+06,6.448786e+06,2.000000e+00,8.500000e+02,NaN,NaN,NaN,NaN,1.800000e+02,1.800000e+02,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,3.466426e+05,3.947781e-02,6.566422e+00,5.540228e+04,2.128286e+05,3.840382e-01,7.980592e+01,NaN,NaN,NaN,NaN,4.049041e+01,1.790930e+01,NaN,NaN

# To Clean Data

* Removal of features not relevant to the prediction model

In [288]:
# Removal of features that should not be used since they do not help predict creditworthiness for a new application.
df = df.drop("loan_id", axis=1) # Excluded because its an identifier, has no predictive relationship with loan default, and does not represent behavior or risk.
df = df.drop("customer_id", axis=1) # Excluded because its an identifier, has no predictive relationship with loan default, and does not represent behavior or risk.
df = df.drop("application_date", axis=1) # The exact date itself is rarely predictive, having nothing to do with loan payment being defaulted or not
df = df.drop("monthly_payment_ngn", axis=1) # This variable is derived from other variables. Including it introduces multicollinearity.
df = df.drop("disbursement_date", axis=1) # This happens after loan approval
df = df.drop("loan_status", axis=1) # Not a pure risk outcome.
df = df.drop("dpd_current", axis=1) # Days Past Due happens after loan repayment begins.
df = df.drop("dpd_max_90d", axis=1) # Same as reasons for dropping dpd_current. It is post-loan behavior.
df = df.drop("default_180d", axis=1) # Happens much later than dpd_max_180d.

In [289]:
df.describe(include="all")

,principal_ngn,interest_rate_annual,tenor_months,salary_ngn,debt_to_income_ratio,credit_score,employment_type,loan_purpose,state,salary_detected,default_90d
count,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2000000,2000000,2000000,2000000,2000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,4,6,37,2,2
top,NaN,NaN,NaN,NaN,NaN,NaN,private_sector,debt_consolidation,Lagos,True,False
freq,NaN,NaN,NaN,NaN,NaN,NaN,899188,500322,476927,1100096,1875628
mean,3.693762e+05,2.401765e-01,1.208589e+01,2.513880e+05,2.930472e-01,6.195735e+02,NaN,NaN,NaN,NaN,NaN
std,3.466426e+05,3.947781e-02,6.566422e+00,2.128286e+05,3.840382e-01,7.980592e+01,NaN,NaN,NaN,NaN,NaN
min,5.000000e+04,1.500000e-01,3.000000e+00,3.000000e+04,7.347331e-04,3.000000e+02,NaN,NaN,NaN,NaN,NaN
25%,1.600000e+05,2.130216e-01,6.000000e+00,1.152108e+05,6.781543e-02,5.660000e+02,NaN,NaN,NaN,NaN,NaN
50%,2.700000e+05,2.400536e-01,1.200000e+01,1.917162e+05,1.518942e-01,6.200000e+02,NaN,NaN,NaN,NaN,NaN
75%,4.600000e+05,2.670563e-01,1.200000e+01,3.170231e+05,3.433757e-01,6.740000e+02,NaN,NaN,NaN,NaN,NaN
max,5.000000e+06,3.500000e-01,3.600000e+01,6.448786e+06,2.000000e+00,8.500000e+02,NaN,NaN,NaN,NaN,NaN

In [290]:
# Let's check the dimension
df.shape

(2000000, 11)

In [291]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 11 columns):
 #   Column                Dtype
---  ------                -----
 0   principal_ngn         float64
 1   interest_rate_annual  float64
 2   tenor_months          int64
 3   salary_ngn            float64
 4   debt_to_income_ratio  float64
 5   credit_score          int64
 6   employment_type       str
 7   loan_purpose          str
 8   state                 str
 9   salary_detected       bool
 10  default_90d           bool
dtypes: bool(2), float64(4), int64(2), str(3)
memory usage: 197.7 MB

### Check unique values to determine and fix inconsistencies

In [292]:
for col in df.columns:
    print(col, df[col].unique())

principal_ngn [ 250000.  370000.  450000.  200000.  270000.  230000.  170000.  390000.
  220000.  180000.  100000.  160000. 1260000. 2440000.  130000.  140000.
  280000.  150000.  260000.  510000.  460000.  300000.  550000.  360000.
  320000.  240000.   50000.  400000.  290000.  120000.  330000.  440000.
 1310000.  110000.  830000.  540000.  770000.  470000.  520000.  340000.
  750000.  380000.  680000.  600000.  190000.  490000.  760000.  210000.
   60000.  480000.  970000. 1580000.  660000.  670000.   70000.  350000.
   80000.  310000.  590000.  720000.  570000.  500000.   90000. 2330000.
  730000.  640000. 1070000.  430000.  820000. 2040000.  690000.  790000.
  620000.  860000.  610000.  410000. 1430000. 1190000.  580000.  420000.
  880000.  850000.  530000.  630000. 1620000. 1000000.  980000. 1500000.
  650000. 1850000. 1180000. 1200000. 1740000.  990000. 1450000. 1670000.
 1420000.  740000. 1280000. 1120000.  900000. 1460000. 2170000. 1910000.
 1020000. 1660000.  840000. 1130000. 1470000.  950000. 2380000.  700000.
 1100000. 1350000. 1530000. 2230000. 1010000.  890000. 2960000.  810000.
 1550000.  940000.  780000.  800000. 2840000. 1370000. 1210000. 1230000.
 1080000.  920000. 1030000. 1160000. 4090000. 1220000. 1060000. 2000000.
  710000. 1140000. 1390000.  870000. 1870000. 1380000.  910000. 1050000.
 3000000. 1640000.  560000. 2240000. 1900000. 1780000. 1990000. 2620000.
 1250000. 2300000. 1240000. 2550000. 1710000. 2430000.  930000. 1830000.
 1490000. 1270000. 1320000. 1570000. 1300000.  960000. 1170000. 1410000.
 1090000. 1480000. 1360000. 2140000. 1800000. 3920000. 1630000. 1650000.
 1040000. 2200000. 1400000. 2080000. 1110000. 2640000. 1590000. 1330000.
 2050000. 2490000. 1540000. 1340000. 1680000. 2130000. 2340000. 2030000.
 2010000. 1890000. 1290000. 1150000. 1560000. 2320000. 1860000. 2540000.
 4470000. 1700000. 1810000. 1750000. 1520000. 1730000. 2990000. 2360000.
 1440000. 2220000. 3260000. 1510000. 1790000. 1760000. 1980000. 2670000.
 3310000. 2690000. 2940000. 2150000. 2570000. 2120000. 1880000. 1970000.
 5000000. 2750000. 3230000. 2370000. 1600000. 2210000. 3250000. 2290000.
 2610000. 1720000. 2420000. 2070000. 3580000. 2020000. 1690000. 1930000.
 3300000. 2190000. 1950000. 2260000. 3080000. 2110000. 2800000. 1940000.
 3170000. 2450000. 2270000. 2180000. 2510000. 1770000. 4270000. 3850000.
 2910000. 3910000. 3140000. 3110000. 2650000. 2390000. 2730000. 2480000.
 2560000. 3840000. 2470000. 2950000. 3120000. 2500000. 3020000. 3820000.
 3740000. 3280000. 1610000. 2760000. 2250000. 4440000. 2520000. 2160000.
 2090000. 2310000. 2710000. 3150000. 2850000. 1920000. 3760000. 3660000.
 2890000. 2100000. 3050000. 1840000. 2680000. 3900000. 2060000. 2900000.
 2770000. 3400000. 3180000. 2400000. 2790000. 2530000. 2810000. 3320000.
 2460000. 3010000. 1960000. 2930000. 3100000. 3130000. 2880000. 3940000.
 1820000. 2590000. 3590000. 2970000. 4340000. 2280000. 2920000. 3600000.
 3550000. 2980000. 3440000. 2830000. 2630000. 3290000. 2860000. 4260000.
 2410000. 3460000. 4710000. 3200000. 4190000. 3380000. 2740000. 3450000.
 4250000. 4650000. 3930000. 2700000. 3980000. 2660000. 4790000. 3270000.
 2580000. 3650000. 4280000. 4100000. 2820000. 4010000. 3420000. 3620000.
 2780000. 3070000. 4540000. 4960000. 3500000. 3190000. 3690000. 2600000.
 4050000. 2870000. 3090000. 4160000. 3670000. 3570000. 3240000. 3360000.
 2350000. 3340000. 2720000. 3390000. 3030000. 4350000. 4380000. 3520000.
 4020000. 3210000. 3640000. 3750000. 3410000. 4570000. 3700000. 4330000.
 4140000. 3860000. 3630000. 3040000. 3880000. 3370000. 4360000. 3480000.
 3790000. 3350000. 3770000. 4810000. 3540000. 3160000. 4670000. 4230000.
 3220000. 4320000. 4490000. 3330000. 3430000. 4830000. 3960000. 4060000.
 3780000. 3830000. 4820000. 3680000. 3730000. 3490000. 3060000. 4400000.
 3890000. 3800000. 3710000. 4120000. 3870000. 4390000. 3610000. 4030000.
 3510000. 3810000. 4040000. 4520000. 3720000. 4290000. 3950000. 4210000.
 3970000. 4940000. 4720000. 4760000. 4930000. 4480000. 4690000. 4680000.
 4610000. 4200000. 4590000. 4780000. 4080000. 3470000. 4970000. 3560000.
 4240000. 4170000. 4110000. 4660000. 4130000. 4450000. 4580000. 4770000.
 4510000. 4180000. 3530000. 4620000. 4000000. 3990000. 4980000. 4630000.
 4870000. 4900000. 4530000. 4150000. 4700000. 4430000. 4990000. 4420000.
 4410000. 4070000. 4740000. 4300000. 4840000. 4910000. 4860000. 4550000.
 4730000. 4850000. 4310000. 4600000. 4750000. 4800000. 4890000. 4560000.
 4370000. 4500000. 4460000. 4640000. 4880000. 4220000.]
interest_rate_annual [0.22931628 0.2630146  0.23542396 ... 0.26975859 0.28188374 0.20530061]
tenor_months [12 18  6 24 36  3]
salary_ngn [ 77316.61051715 687453.89717266 586733.82002719 ... 218060.39970323
 371119.31537335  90720.02946043]
debt_to_income_ratio [0.30408513 0.05149502 0.07235347 ... 0.06604062 0.43805576 0.21435881]
credit_score [696 659 616 539 711 578 535 490 587 654 580 618 542 529 468 614 776 518
 786 680 640 644 592 594 549 547 558 727 686 707 604 579 755 679 638 667
 556 687 697 606 546 590 505 501 564 693 726 520 648 677 824 662 492 689
 658 581 436 625 532 651 506 665 597 647 645 664 610 774 657 739 524 487
 660 642 682 622 596 623 462 605 570 759 688 656 583 573 643 633 469 678
 527 748 624 740 702 459 699 628 663 728 584 617 463 560 669 598 673 805
 589 603 779 704 798 572 631 641 495 649 784 582 818 698 503 567 750 621
 576 557 639 588 675 674 653 591 602 551 620 405 632 683 548 565 566 706
 761 507 608 825 530 619 454 427 762 481 536 511 668 615 694 652 568 561
 710 516 661 708 470 752 611 751 593 497 637 609 585 685 797 554 790 488
 635 515 575 601 484 722 607 719 764 483 725 523 850 729 571 655 471 765
 742 629 817 473 691 700 666 531 717 562 692 550 743 746 676 494 577 432
 600 749 458 671 534 540 630 394 626 613 553 773 634 513 525 695 670 510
 721 599 410 559 650 684 543 646 718 701 732 734 809 480 595 735 709 758
 491 512 783 461 574 627 766 444 736 528 690 586 714 423 756 477 703 636
 412 705 672 775 472 785 744 538 760 442 724 715 738 723 563 508 713 364
 768 545 569 387 555 745 792 781 793 479 552 457 533 489 541 788 409 767
 502 443 681 504 431 537 712 467 475 810 474 496 509 612 486 498 499 448
 400 737 514 445 730 544 754 741 843 415 526 716 500 787 763 521 720 772
 451 449 395 464 839 812 791 517 522 782 456 733 770 441 437 366 799 795
 493 476 747 821 780 822 452 816 771 478 811 845 769 418 777 757 446 392
 802 300 455 731 453 416 482 428 447 803 354 359 398 433 358 838 796 519
 466 778 414 460 391 426 835 439 419 834 406 801 407 815 465 753 819 381
 422 402 485 420 403 376 800 823 386 804 378 794 808 421 373 425 438 424
 807 353 429 393 789 440 382 365 828 399 401 397 814 820 371 396 826 390
 849 450 430 829 413 806 350 837 318 813 434 846 380 379 836 417 339 356
 847 332 827 833 346 435 841 344 370 375 840 830 363 831 411 361 372 383
 343 848 388 384 404 362 842 368 408 389 351 832 324 385 355 347 342 844
 311 360 352 330 319 367 327 337 374 306 369 333 340 331 377 314 345 326
 357 348 349 329 325 336 338 307 308 317 301 322 312 334 341 303 313 310
 328 335 323 315 304 316 309 321 320 305 302]
employment_type <ArrowStringArray>
['private_sector', 'government', 'self_employed', 'unemployed']
Length: 4, dtype: str
loan_purpose <ArrowStringArray>
[          'personal',            'medical',          'education',
 'debt_consolidation',   'home_improvement',           'business']
Length: 6, dtype: str
state <ArrowStringArray>
[    'Plateau',      'Jigawa',       'Lagos',   'Akwa Ibom',       'Niger',
 'Abuja (FCT)',      'Kaduna',       'Enugu',        'Ogun',        'Kano',
     'Katsina',         'Oyo',      'Rivers',     'Anambra',        'Abia',
       'Kwara',       'Ekiti',     'Adamawa',        'Yobe',       'Benue',
         'Edo',       'Delta',       'Gombe',       'Kebbi',       'Borno',
         'Imo',      'Bauchi',      'Taraba',        'Osun',      'Sokoto',
        'Ondo', 'Cross River',     'Zamfara',        'Kogi',    'Nasarawa',
      'Ebonyi',     'Bayelsa']
Length: 37, dtype: str
salary_detected [ True False]
default_90d [False  True]

* Check for missing values

In [293]:
df.isna().sum()

principal_ngn           0
interest_rate_annual    0
tenor_months            0
salary_ngn              0
debt_to_income_ratio    0
credit_score            0
employment_type         0
loan_purpose            0
state                   0
salary_detected         0
default_90d             0
dtype: int64

* To check for duplicates entries

In [294]:
print(df.duplicated().sum())

0

# Check for Outliers

In [295]:
df.describe()

,principal_ngn,interest_rate_annual,tenor_months,salary_ngn,debt_to_income_ratio,credit_score
count,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06
mean,3.693762e+05,2.401765e-01,1.208589e+01,2.513880e+05,2.930472e-01,6.195735e+02
std,3.466426e+05,3.947781e-02,6.566422e+00,2.128286e+05,3.840382e-01,7.980592e+01
min,5.000000e+04,1.500000e-01,3.000000e+00,3.000000e+04,7.347331e-04,3.000000e+02
25%,1.600000e+05,2.130216e-01,6.000000e+00,1.152108e+05,6.781543e-02,5.660000e+02
50%,2.700000e+05,2.400536e-01,1.200000e+01,1.917162e+05,1.518942e-01,6.200000e+02
75%,4.600000e+05,2.670563e-01,1.200000e+01,3.170231e+05,3.433757e-01,6.740000e+02
max,5.000000e+06,3.500000e-01,3.600000e+01,6.448786e+06,2.000000e+00,8.500000e+02

The steps below is to automatically detect and treat outliers in all numeric columns in the cleaned dataset using the IQR (Interquartile Range) method

In [296]:
# Automatically Detect Numeric Columns
numeric_cols = df.select_dtypes(include=['int64','float64']).columns

print("Numeric Columns:")
print(numeric_cols)

Numeric Columns:
Index(['principal_ngn', 'interest_rate_annual', 'tenor_months', 'salary_ngn',
       'debt_to_income_ratio', 'credit_score'],
      dtype='str')

In [297]:
# Detect Outliers in All Numeric Columns
outlier_summary = {}

for col in numeric_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    outlier_summary[col] = len(outliers)

print("Outlier Count Per Column")
print(outlier_summary)

Outlier Count Per Column
{'principal_ngn': 124943, 'interest_rate_annual': 6933, 'tenor_months': 199417, 'salary_ngn': 112099, 'debt_to_income_ratio': 184850, 'credit_score': 13661}

In [298]:
# Automatically Treat Outliers (Capping Method)
for col in numeric_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower, upper)

In [299]:
# To verify That Outliers Are Removed
check_outliers = {}

for col in numeric_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    check_outliers[col] = len(outliers)

print("Remaining Outliers After Treatment")
print(check_outliers)

Remaining Outliers After Treatment
{'principal_ngn': 0, 'interest_rate_annual': 0, 'tenor_months': 0, 'salary_ngn': 0, 'debt_to_income_ratio': 0, 'credit_score': 0}

In [303]:
df.shape

(2000000, 11)

In [300]:
df.to_csv('cleaned_data.csv', index=False)